Rails.application.routes.draw do
  # Authentication (generated by Rails 8)
  resource :session
  resources :passwords, param: :token

  # Registration
  get "signup", to: "registrations#new"
  post "signup", to: "registrations#create"

  # Main feed (home page when logged in)
  root "feed#index"

  # Situations (status updates)
  resources :situations, only: [:create, :destroy]

  # User profiles
  resources :users, only: [:show], param: :username

  # Following
  resources :follows, only: [:create, :destroy]

  # Tags management
  resources :tags, only: [:index, :create, :destroy]

  # Account settings
  get "settings/account", to: "settings#account"
  patch "settings/account", to: "settings#update_account"
  patch "settings/password", to: "settings#update_password"

  # Health check
  get "up" => "rails/health#show", as: :rails_health_check
end
